# Copyright 2023 NOCI_Jax developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
'''
Using Jax data structures.
'''
import numpy as np
import jax.numpy as jnp
import jax
from jax.config import config
config.update("jax_enable_x64", True)
# import os 
# os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]="false"
# os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]=".XX"
# os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"]="platform"


def tvecs_to_rmats(tvecs, nvir, nocc, occ_mat=None):
    '''
    Transform Thouless vectors into rotation matrices.
    Args:
        tvecs: array, can be size (N, 2*nvir*nocc), (2*nvir*nocc) or (N, 2, nvir, nocc).
        nvir: int, number of virtual orbitals.
        nocc: int, number of occupied orbitals.
    Kwargs:
        occ_mat: the rotation matrices for the occupied orbitals.
    Returns:
        array of size (N, 2, nvir, nocc)
    '''

    vecs_all = tvecs.reshape(-1, nvir, nocc)
    nvecs = vecs_all.shape[0]
    if occ_mat is None:
        occ_mat = jnp.eye(nocc)
    Imats = jnp.tile(occ_mat, (nvecs)).T.reshape(nvecs, nocc, nocc) # 2 for spins
    rmats = jnp.concatenate([Imats, vecs_all], axis=1)
    rmats = rmats.reshape(-1, 2, nvir+nocc, nocc)
    return rmats

def add_tvec_hf(tmats):
    '''
    Add the Hartree-Fock Thouless matrices to the list of Thouless
    '''
    t0 = np.zeros_like(tmats[0])[None, :] # add another axis
    t_all = np.vstack([t0, tmats])
    return t_all

def gen_rmat_hf(nvir, nocc):
    rot0_u = jnp.zeros((nvir+nocc, nocc))
    rot0_u = rot0_u.at[:nocc, :nocc].set(jnp.eye(nocc))
    rmats_new = jnp.array([[rot0_u, rot0_u]]) # the HF state

    return rmats_new

def metric_rmats(rmat1, rmat2):
    '''
    Evaluate the overlap between the two Slater determinants represented by rotation matrices.
    '''
    mat = jnp.einsum('sji, sjk -> sik', rmat1.conj(), rmat2)
    ovlp = jnp.prod(jnp.linalg.det(mat), axis=-1)

    return ovlp


def orthonormal_mos(tmats):
    '''
    Get the orthonormalization matrix given a Thouless rotation. 
    Args:
        tmat: 3D array or 4D array, the thouless rotation of size (nt, spin, nvir, nocc)
    Returns:
        3D array: full rotation matrices to generate the new set of MOs.
    '''
    tshape = tmats.shape
    if len(tshape) <= 2: # matrices
        nvir, nocc = tshape
        norb = nvir + nocc
        Iocc = np.eye(nocc)
        Ivir = np.eye(nvir)

        Mocc = np.linalg.inv(Iocc + tmats.T.conj()@tmats).T.conj()
        Mvir = np.linalg.inv(Ivir + tmats@tmats.T.conj()).T.conj()
        Uocc = np.linalg.cholesky(Mocc)
        Uvir = np.linalg.cholesky(Mvir)
        mat_on = np.zeros((norb, norb))
        mat_on[:nocc, :nocc] = Uocc 
        mat_on[nocc:, :nocc] = tmats@Uocc 
        mat_on[:nocc, nocc:] = -tmats.conj().T@Uvir 
        mat_on[nocc:, nocc:] =  Uvir

    else: # more than one matrices
        Nt = np.prod(tshape[:-2])
        nvir, nocc = tshape[-2:]
        norb = nocc + nvir
        Iocc = np.eye(nocc)
        Ivir = np.eye(nvir)
        ts = tmats.reshape(Nt, nvir, nocc)

        Mocc = np.tile(Iocc, Nt).T.reshape(Nt, nocc, nocc)\
            + np.moveaxis(ts, -2, -1).conj()@ts
        Mvir = np.tile(Ivir, Nt).T.reshape(Nt, nvir, nvir)\
            + ts@np.moveaxis(ts, -2, -1).conj()

        Uocc = np.linalg.cholesky(Mocc)
        Uocc = np.moveaxis(np.linalg.inv(Uocc), -2, -1).conj()
        Uvir = np.linalg.cholesky(Mvir)
        Uvir = np.moveaxis(np.linalg.inv(Uvir), -2, -1).conj()

        mat_on = np.zeros((Nt, norb, norb))
        mat_on[:, :nocc, :nocc] = Uocc 
        mat_on[:, nocc:, :nocc] = ts@Uocc
        mat_on[:, :nocc, nocc:] = -np.moveaxis(ts, -2, -1).conj()@Uvir 
        mat_on[:, nocc:, nocc:] = Uvir 
        
    return mat_on.reshape(*list(tmats.shape[:-2]), norb, norb)

def rotate_rmats(rmats, U):
    '''
    Rotate the rmats based on Unitary matrix U.
    args:
        rmats: (nr, s, norb, nocc) array
        U: (s, norb, norb) array
    Returns:
        UR for each R
    '''
    return jnp.einsum('sij, nsjk -> nsik', U, rmats)


def noci_energy(rmats, mo_coeff, h1e, h2e, return_mats=False, lc_coeffs=None, e_nuc=0.0):
    '''
    NOCI energy from the determinants generated by rmats.
    Returns:
        float
    '''

    if return_mats:
        return noci_matrices(rmats, mo_coeff, h1e, h2e)

    if lc_coeffs is not None:
        return noci_energy_lc(rmats, mo_coeff, h1e, h2e, lc_coeffs, e_nuc)

    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)

    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, inv_metrics, sdets.conj())

    # transition hamiltonian
    E1 = jnp.einsum("ij, nmsji -> nm", h1e, trdms)
    J = jnp.einsum("ijkl, nmslk -> nmij", h2e, trdms)
    E2J = jnp.einsum("nmij, nmsji -> nm", J, trdms)
    K = jnp.einsum("ijkl, nmsjk -> nmsil", h2e, trdms)
    E2K = jnp.einsum("nmsij, nmsji ->nm", K, trdms)

    E2 = E2J - E2K

    hmat = (E1 + 0.5*E2) * smat

    energy = solve_lc_coeffs(hmat, smat, return_vec=False)
    return energy + e_nuc

@jax.jit
def noci_energy_jit(rmats, mo_coeff, h1e, h2e, return_mats=False, lc_coeffs=None, 
                    e_nuc=0.0, return_vec=False):
    '''
    NOCI energy from the determinants generated by rmats.
    Returns:
        float
    '''

    if return_mats:
        return noci_matrices(rmats, mo_coeff, h1e, h2e)

    if lc_coeffs is not None:
        return noci_energy_lc(rmats, mo_coeff, h1e, h2e, lc_coeffs, e_nuc)

    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)
    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, inv_metrics, sdets.conj())

    # transition hamiltonian
    E1 = jnp.einsum("ij, nmsji -> nm", h1e, trdms)
    J = jnp.einsum("ijkl, nmslk -> nmij", h2e, trdms)
    E2J = jnp.einsum("nmij, nmsji -> nm", J, trdms)
    K = jnp.einsum("ijkl, nmsjk -> nmsil", h2e, trdms)
    E2K = jnp.einsum("nmsij, nmsji ->nm", K, trdms)

    E2 = E2J - E2K

    hmat = (E1 + 0.5*E2) * smat

    if return_vec:
        energy, c = solve_lc_coeffs(hmat, smat, return_vec=True)
        return energy + e_nuc, c
    else:
        energy = solve_lc_coeffs(hmat, smat, return_vec=False)
        return energy + e_nuc

@jax.jit
def noci_energy_lc(rmats, mo_coeff, h1e, h2e, lc_coeffs, e_nuc=0.0):
    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)

    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, jnp.linalg.inv(metrics_all), sdets.conj())
    sdets = None
    metrics_all = None
    
    # E1 = jnp.einsum("")
    # transition hamiltonian
    E1 = jnp.einsum("ij, nmsji -> nm", h1e, trdms)
    J = jnp.einsum("ijkl, nmslk -> nmij", h2e, trdms)
    J = jnp.einsum("nmij, nmsji -> nm", J, trdms)
    K = jnp.einsum("ilkj, nmslk -> nmsij", h2e, trdms)
    K = jnp.einsum("nmsij, nmsji ->nm", K, trdms)
    E2 = J - K
    # E2 = E2J - E2K
    trdms = None

    hmat = (E1 + 0.5*E2) * smat

    h = lc_coeffs.T.conj().dot(hmat).dot(lc_coeffs)
    s = lc_coeffs.T.conj().dot(smat).dot(lc_coeffs)
    energy = (h / s)

    return energy + e_nuc


def noci_matrices(rmats, mo_coeff, h1e, h2e):
    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)
    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, inv_metrics, sdets.conj())

    # transition hamiltonian
    E1 = jnp.einsum("ij, nmsji -> nm", h1e, trdms)
    J = jnp.einsum("ijkl, nmslk -> nmij", h2e, trdms)
    E2J = jnp.einsum("nmij, nmsji -> nm", J, trdms)
    K = jnp.einsum("ijkl, nmsjk -> nmsil", h2e, trdms)
    E2K = jnp.einsum("nmsij, nmsji ->nm", K, trdms)

    E2 = E2J - E2K

    hmat = (E1 + 0.5*E2) * smat
    return hmat, smat


def solve_lc_coeffs(hmat, smat, return_vec=False):
    '''
    Solve the eigenvalue problem Hc = ESc. 
    
    Returns:
        double, ground state energy
        if return_vec:
            1D array, linear combination coefficient
    '''
    energy, c = _generalized_eigh(hmat, smat)

    if return_vec:
        return energy, c
    else:
        return energy
    

def make_rdm1(rmats, mo_coeff, lc_coeff):
    '''
    Make rdm1 of NOCI in the AO basis for UHF.
    Return: array of size (2, N, N)
    '''
    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)
    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, inv_metrics, sdets.conj())
    trdms = jnp.einsum("nmsij, nm -> nmsij", trdms, smat)

    top = jnp.einsum("n, m, nmsij -> sij", lc_coeff.conj(), lc_coeff, trdms) 
    bot = jnp.einsum("n, m, nm ->", lc_coeff.conj(), lc_coeff, smat)

    return top/bot


def make_rdm12(rmats, mo_coeff, lc_coeff):
    '''
    Make 2RDM given an NOCI.
    Return: (p,q,r,s) = <a^dag_p a_q a^_r a_s>
    order: uuuu, uudd, dduu, dddd

    '''
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)
    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)
    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets, inv_metrics, sdets.conj())
    dm1s = jnp.einsum("nmsij, nm -> nmsij", trdms, smat)
    dm1_u = trdms[:, :, 0]
    dm1_d = trdms[:, :, 1]
    dm2s_uu = jnp.einsum("nmij, nmkl -> nmijkl", dm1_u, dm1_u) \
             - jnp.einsum("nmil, nmkj -> nmijkl", dm1_u, dm1_u)
    dm2s_dd = jnp.einsum("nmij, nmkl -> nmijkl", dm1_d, dm1_d) \
             - jnp.einsum("nmil, nmkj -> nmijkl", dm1_d, dm1_d)
    dm2s_ud = jnp.einsum("nmij, nmkl -> nmijkl", dm1_u, dm1_d)
    dm2s_du = jnp.einsum("nmij, nmkl -> nmijkl", dm1_d, dm1_u)

    dm2s = jnp.array([dm2s_uu, dm2s_ud, dm2s_du, dm2s_dd])
    dm2s = jnp.einsum("snmijkl, nm -> snmijkl", dm2s, smat)

    dm1s = jnp.einsum("n, m, nmsij -> sij", lc_coeff.conj(), lc_coeff, dm1s) 
    dm2s = jnp.einsum("n, m, snmijkl -> sijkl", lc_coeff.conj(), lc_coeff, dm2s)


    phi_norm = jnp.einsum("n, m, nm ->", lc_coeff.conj(), lc_coeff, smat)

    return dm1s/phi_norm, dm2s/phi_norm


def make_rdm12_diag(rmats, mo_coeff, lc_coeff):
    '''
    Only make the diagonal term of the 2RDM of <up+ up dn+ dn>.
    The diagonal of rdm1 and rdm2.
    Return: (p,q) = <a^dag_p a_p a^_q a_q>
    '''
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(np.linalg.det(metrics_all), axis=-1)

    try:
        ndim = mo_coeff.ndim 
    except:
        ndim = 3
        mo_coeff = jnp.asarray(mo_coeff)
    if ndim > 2:
        sdets = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats)
    else:
        sdets = jnp.einsum("ij, nsjk -> nsik", mo_coeff, rmats)

    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    trdms_diag = jnp.einsum("msij, nmsjk, nsik -> nmsi", sdets, inv_metrics, sdets.conj())
    dm1s_diag = jnp.einsum("nmsi, nm -> nmsi", trdms_diag, smat)
    dm1_u = trdms_diag[:, :, 0]
    dm1_d = trdms_diag[:, :, 1]

    dm2s_ud = jnp.einsum("nmi, nmj -> nmij", dm1_u, dm1_d)
    dm2s_ud = jnp.einsum("nmij, nm -> nmij", dm2s_ud, smat)

    dm1s_diag = jnp.einsum("n, m, nmsi -> si", lc_coeff.conj(), lc_coeff, dm1s_diag) 
    dm2s_ud = jnp.einsum("n, m, nmij -> ij", lc_coeff.conj(), lc_coeff, dm2s_ud)

    phi_norm = jnp.einsum("n, m, nm ->", lc_coeff.conj(), lc_coeff, smat)
    return dm1s_diag/phi_norm, dm2s_ud/phi_norm


def get_smat(rmats):
    '''
    Get the overlap matrix of the given determinants.
    '''
    metrics = jnp.einsum('nsji, msjk -> nmsik', rmats.conj(), rmats)
    smat = jnp.prod(jnp.linalg.det(metrics), axis=-1)   
    return smat

def expand_hs(hmat0, smat0, rmats_n, rmats_fix, h1e, h2e, mo_coeff):
    '''
    Expand the H matrix and S matrix
    | (fix, fix)   (fix, n)|
    | (n, fix)     (n, n)  |
    (fix, fix) is given by h_n and s_n
    we evaluate (n, fix) and (n, n)  
    '''
    n_fix = len(rmats_fix)
    n_new = len(rmats_n)
    n_tot = n_fix + n_new
    
    hm = jnp.zeros((n_tot, n_tot))
    sm = jnp.zeros((n_tot, n_tot))
    hm = hm.at[:n_fix, :n_fix].set(hmat0)
    sm = sm.at[:n_fix, :n_fix].set(smat0)

    # generate hmat and smat for the lower left block and upper right block
    h_new, s_new = _gen_hsmat(rmats_n, rmats_fix, mo_coeff, h1e, h2e)
    hm = hm.at[n_fix:, :n_fix].set(h_new)
    hm = hm.at[:n_fix, n_fix:].set(h_new.T.conj())
    sm = sm.at[n_fix:, :n_fix].set(s_new)
    sm = sm.at[:n_fix, n_fix:].set(s_new.T.conj())

    # generate hmat and smat for the lower diagonal block
    h_new, s_new = noci_energy(rmats_n, mo_coeff, h1e, h2e, return_mats=True)
    hm = hm.at[n_fix:, n_fix:].set(h_new)
    sm = sm.at[n_fix:, n_fix:].set(s_new)

    return hm, sm


def expand_smat(smat_fix, rmats_fix, rmats_new):
    '''
    Given the previous smat from rmats_fix, add the rows and columns from
    rmats_new.
    '''
    n_fix = len(rmats_fix)
    n_new = len(rmats_new)
    n_tot = n_fix + n_new
    metrics_mix = jnp.einsum('nsji, msjk -> nmsik', rmats_fix.conj(), rmats_new)
    smat_left = jnp.prod(jnp.linalg.det(metrics_mix), axis=-1)
    metrics_new = jnp.einsum('nsji, msjk -> nmsik', rmats_new.conj(), rmats_new)
    smat_new = jnp.prod(jnp.linalg.det(metrics_new), axis=-1)

    smat = jnp.zeros((n_tot, n_tot))
    smat = smat.at[:n_fix, :n_fix].set(smat_fix)
    smat = smat.at[:n_fix, n_fix:].set(smat_left)
    smat = smat.at[n_fix:, :n_fix].set(smat_left.conj().T)
    smat = smat.at[n_fix:, n_fix:].set(smat_new)

    return smat
    


def _gen_hsmat(rmats1, rmats2, mo_coeff, h1e, h2e):
    '''
    Return the matrices of the Hamiltonian and overlap matrix with
    respect to two sets of rotation matrices.
    '''

    # first calculate metric and thus overlap
    metrics_all = jnp.einsum('nsji, msjk -> nmsik', rmats1.conj(), rmats2)
    smat = jnp.prod(jnp.linalg.det(metrics_all), axis=-1)

    # transition density matrices
    inv_metrics = jnp.linalg.inv(metrics_all)
    sdets1 = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats1)
    sdets2 = jnp.einsum("sij, nsjk -> nsik", mo_coeff, rmats2)
    trdms = jnp.einsum("msij, nmsjk, nslk -> nmsil", sdets2, inv_metrics, sdets1.conj())

    # transition hamiltonian
    E1 = jnp.einsum("ij, nmsji -> nm", h1e, trdms)
    J = jnp.einsum("ijkl, nmslk -> nmij", h2e, trdms)
    E2J = jnp.einsum("nmij, nmsji -> nm", J, trdms)
    K = jnp.einsum("ijkl, nmsjk -> nmsil", h2e, trdms)
    E2K = jnp.einsum("nmsij, nmsji ->nm", K, trdms)

    E2 = E2J - E2K
    hmat = (E1 + 0.5*E2) * smat
   
    return hmat, smat


def _generalized_eigh(A, B):
    L = jnp.linalg.cholesky(B)
    L_inv = jnp.linalg.inv(L)
    A_redo = L_inv @ A @ L_inv.T
    e, v = jnp.linalg.eigh(A_redo)
    e0 = e[0]
    v0 = v[:, 0]
    c0 = L_inv.T @ v0 # rotate back 

    return e0, c0

if __name__ == "__main__":
    print("Main function:\n")
